version: "3"

services:
  vc-api:
    container_name: voice-conversion-api
    build: .
    restart: always
    networks:
      - vcnetwork
    runtime: nvidia  # GPU 런타임 설정
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./:/workspace
    ports:
      - 1513:1513
      - 1900:1900
    command: bash -c "uvicorn api:app --host 0.0.0.0  --port 1900 --workers 1 --reload"